spring:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/exam11_db
    username: springuser
    password: ThePassword
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    path: /api-page.html
  api-docs:
    path: /api-docs
